### ISSUE TITLE
Navigating Back from Instance view crash

### ISSUE THREAD

**Issue by willpowr** [willpowr/EventLamp#49]

**Comment by willpowr** [comment]
java.lang.IllegalStateException: FragmentManager is already executing transactions
                                         at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2167)
                                         at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2195)
                                         at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                         at com.willpoweru.eventlamp.ui.main.MainActivity.invokeInstancesFragment(MainActivity.java:577)
                                         at com.willpoweru.eventlamp.ui.main.MainActivity.refreshList(MainActivity.java:816)
                                         at com.willpoweru.eventlamp.ui.main.MainActivity$2.onBackStackChanged(MainActivity.java:222)
                                         at android.support.v4.app.FragmentManagerImpl.reportBackStackChanged(FragmentManager.java:2697)
                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2395)
                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                         at android.os.Handler.handleCallback(Handler.java:790)
                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                         at android.os.Looper.loop(Looper.java:164)
                                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
